### ISSUE TITLE
Create a tester package

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/DBI#2]
A package `DBI.test` that exports a single function that runs all tests on a specific backend. Called from a file in `tests/testthat`. New backends can use these "standard" tests right away.

- [ ] Think about a way to specify options what to test.
- [ ] Merge existing tests into this package

**Comment by hadley** [comment]
I'd prefer no `.` in the package name, but otherwise sounds good :)

**Comment by hadley** [comment]
I suspect the package could be arranged around lists of testing functions for given topics. If each test had a brief name, it should be possible to add some infrastructure to drop tests matching a given name:

```R
test_creation <- function(db, skip = NULL) {
   tests <- list(
     character = function(db) {...},
     date = function(db) {...},
  )
  ...
}
```

Then the packages being tested would call the functions from DBItest they want to use

**Comment by krlmlr** [comment]
Done.
